In [1]:
import pandas as pd

In [5]:
pd.read_json("row_format.jsonl", lines=True)

            model   type  price
0  Toyota Corolla  Sedan  22000
1     Toyota RAV4    SUV  30000
2    Toyota Camry  Sedan  28000

In [6]:
df = pd.read_json("row_format.jsonl", lines=True)

In [7]:
type(df)

pandas.DataFrame

In [9]:
df.columns

Index(['model', 'type', 'price'], dtype='str')

In [12]:
df[["model", "price"]]

            model  price
0  Toyota Corolla  22000
1     Toyota RAV4  30000
2    Toyota Camry  28000

In [14]:
pd.read_json("column_format.json")

     model   type  price
0  Corolla  Sedan  22000
1     RAV4    SUV  28000
2    Camry  Sedan  26000

In [15]:
df

            model   type  price
0  Toyota Corolla  Sedan  22000
1     Toyota RAV4    SUV  30000
2    Toyota Camry  Sedan  28000

In [17]:
df.to_dict()

{'model': {0: 'Toyota Corolla', 1: 'Toyota RAV4', 2: 'Toyota Camry'},
 'type': {0: 'Sedan', 1: 'SUV', 2: 'Sedan'},
 'price': {0: 22000, 1: 30000, 2: 28000}}

In [18]:
df.to_dict(orient="records")

[{'model': 'Toyota Corolla', 'type': 'Sedan', 'price': 22000},
 {'model': 'Toyota RAV4', 'type': 'SUV', 'price': 30000},
 {'model': 'Toyota Camry', 'type': 'Sedan', 'price': 28000}]